# ANDROID_BUILD_VERSION=30
# ANDROID_TOOLS_VERSION=30.0.3
# NODE_VERSION=14.x
image: reactnativecommunity/react-native-android

pipelines:
  default:
    - step:
        size: 2x
        name: NPM Install
        caches:
          - node
        script:
          - npm i -g envinfo && envinfo

    - step:
        size: 2x
        name: Yarn
        caches:
          - node
        script:
          - yarn config set network-timeout 600000
          - yarn install

    - step:
        size: 2x
        name: Gradle
        caches:
          - node
          - gradle
        script:
          - cd android
          - chmod +x gradlew
          - ./gradlew bundleRelease assembleRelease
        artifacts:
          - app/build/outputs/**
